language: rust
sudo: false
rust:
  - beta
  - nightly
services:
  - redis-server
env:
  - CRATE=.
  - CRATE=spaceapi
  - CRATE=spaceapi_server
script: cd $CRATE && cargo build --verbose && cargo test --verbose
notifications:
  irc:
    channels:
      - "chat.freenode.net#coredump"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
