language: rust
rust: nightly
services:
  - redis-server
notifications:
  irc:
    channels:
      - "chat.freenode.net#coredump"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
