[package]
name = "coredump_status"
version = "0.0.1"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
]
repository = "https://github.com/coredump-ch/spaceapi"
readme = "./README.rst"
keywords = ["json", "spaceapi"]

[dependencies.spaceapi]
path = "spaceapi"

[dependencies.spaceapi_server]
path = "spaceapi_server"

[dependencies]
docopt = "*"
rustc-serialize = "*"
env_logger = "*"
