[package]
name = "spaceapi"
version = "0.0.1"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
]
repository = "https://github.com/coredump-ch/spaceapi"
readme = "./README.rst"
keywords = ["json", "spaceapi"]

[dependencies]
rustc-serialize = "0.3.14"
hyper = "0.3.16"
redis = "0.3.1"
