[package]
name = "spaceapi"
version = "0.1.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
]

[dependencies]
rustc-serialize = "^0.3"
log = "^0.3"
