[package]
name = "spaceapi_server"
version = "0.1.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
]

[dependencies]
redis = "^0.3"
rustc-serialize = "^0.3"
iron = "^0.1"
log = "^0.3"
urlencoded = "^0.2"

[dependencies.spaceapi]
path = "../spaceapi"
