[package]
name = "spaceapi_server"
version = "0.1.0"
authors = [
    "Raphael Nestler <raphael.nestler@gmail.com>",
    "Danilo Bargen <mail@dbrgn.ch>",
]

[dependencies]
redis = "^0.5"
rustc-serialize = "^0.3"
iron = "^0.2"
log = "^0.3"
urlencoded = "^0.2"
router = "^0.0.15"
error-type = "^0.1"

[dependencies.spaceapi]
path = "../spaceapi"
